### ISSUE TITLE
Upgrade to Specflow 4.0

### ISSUE THREAD

**Issue by indcoder** [HackerspaceMumbai/Visage#64]
```[tasklist]
### Tasks
- [ ] https://github.com/HackerspaceMumbai/Visage/issues/59
- [ ] Create an experimental Specflow 4.0  project
- [ ] Validate new nuget package
```
